// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:197813352454:web:cb778af9279b188ce52b87',
    messagingSenderId: '197813352454',
    projectId: 'week05-7526a',
    authDomain: 'week05-7526a.firebaseapp.com',
    storageBucket: 'week05-7526a.firebasestorage.app',
    measurementId: 'G-W3FMGK61G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:197813352454:android:e8054461761cc379e52b87',
    messagingSenderId: '197813352454',
    projectId: 'week05-7526a',
    storageBucket: 'week05-7526a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:197813352454:ios:15386f25f40af5aae52b87',
    messagingSenderId: '197813352454',
    projectId: 'week05-7526a',
    storageBucket: 'week05-7526a.firebasestorage.app',
    iosClientId: '197813352454-tbgspfasb8tspcos5r0d409jq2kadg48.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:197813352454:ios:15386f25f40af5aae52b87',
    messagingSenderId: '197813352454',
    projectId: 'week05-7526a',
    storageBucket: 'week05-7526a.firebasestorage.app',
    iosClientId: '197813352454-tbgspfasb8tspcos5r0d409jq2kadg48.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:197813352454:web:73d6dd9e230fb730e52b87',
    messagingSenderId: '197813352454',
    projectId: 'week05-7526a',
    authDomain: 'week05-7526a.firebaseapp.com',
    storageBucket: 'week05-7526a.firebasestorage.app',
    measurementId: 'G-SXHDMKN8V5',
  );
}
